image: rikorose/gcc-cmake

# Download all dependencies
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build
    
test:
  stage: test
  dependencies:
      - build
  script:
    - cd build; ctest
